dateFormat: '%Y%m%d'

logging:
  level: DEBUG

DB:
  host: 192.168.31.73
  port: 3306
  schema: gambling_simulation
  user: allen
  password: aldbpw

crawler:
  urlPattern: https://www.playsport.cc/predictgame.php?action=scale&allianceid={game_type}&gametime={game_date}&sid={group_type}

commander:
  queryPeriod: 5 # second
  availableInterval: 365 # day
  gameTypes:
    - NBA
    - MLB
    - NPB

mongo:
  db: kais
  host: localhost
  port: 27017
  username:
  password: